name: Build and Test C Code

on:
  workflow_dispatch: # מאפשר הפעלה ידנית בלבד

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile the program
        run: |
          gcc -o game game.c colorPrint.c getch.c minesweeper.c

      - name: Run the program
        run: ./game
